# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B63Jz8BdZ5RL1ft9FmBU-lLF8tEF5Nfr
"""

# import the opencv library
import cv2


# define a video capture object
vid = cv2.VideoCapture(0)

while(True):
  ret, frame = vid.read()
  cv2.imshow('frame', frame)
  if cv2.waitKey(1) & 0xFF == ord('q'):
    break

# After the loop release the cap object
vid.release()
# Destroy all the windows
cv2.destroyAllWindows()